# Generated by Django 3.2.4 on 2021-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travallo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='mane',
            new_name='nane',
        ),
    ]
