# Generated by Django 3.2.4 on 2021-06-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travallo', '0002_rename_mane_destination_nane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='nane',
            new_name='name',
        ),
    ]
